# Site Configuration for PET Bottles Manufacturing Business
title: "Ganpati Industries - PET Bottles Manufacturing"
description: "High-quality PET plastic bottles for mustard oil, cooking oils, and food packaging. Custom manufacturing with competitive pricing and fast delivery in and around Punjab."
baseurl: ""
url: "https://ganpatimansa.com"

# Business Information
business_name: "Ganpati Industries Mansa"
business_tagline: "Quality Packaging Solutions for Food Industry"
business_address: "Talwandi Road, Mansa, India"
business_phone: "+91-94174-57799"
business_email: "vikrantgarg.gi@gmail.com"
business_whatsapp: "919417457799"
api_contact_url: "https://script.google.com/macros/s/AKfycbz1XMH6_4dFL8kXm_P6PgJanLXVflhYirxjKljz7y1Proe0danawXnL4DjOJ2T6PEzVlg/exec"

# SEO Settings
author: "Ganpati Industries Mansa - PET Bottles"
keywords: "PET bottles, plastic bottles, mustard oil bottles, cooking oil bottles, food packaging, custom bottles, manufacturing, India"

# Collections
collections:
  products:
    output: true
    permalink: /products/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Plugins (Privacy-Conscious)
plugins:
  - jekyll-sitemap
  # Removed jekyll-feed and jekyll-seo-tag to prevent tracking

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
